adon_MAINTAINERCLEAN_FILES:= adon-files.mk \
		Makefile.real \
		rules.mk \
		vardefs.mk \
		Makefile \
		Rules-debug.mk \
		env-tests/compile-test.sh \
		env-tests/env-lib.mk \
		env-tests/env-pthread-kirpich.mk \
		env-tests/env-wstring-kirpich.mk \
		env-tests/zthread-kirpich.cpp \
		env-tests/boost-thread-kirpich.cpp \
		env-tests/env-lib.sh \
		env-tests/env-cxx-flag-kirpich.mk \
		env-tests/env-zthread-kirpich.mk \
		env-tests/wstring-kirpich.cpp \
		env-tests/pthread-kirpich.c \
		env-tests/cxx-gen-kirpich.cpp \
		env-tests/link-test.sh \
		env-tests/env-boost-thread-kirpich.mk \
		env-tests/env-tests.mk \
