PKG_NAME:=libebt
PACKAGE:=$(PKG_NAME)
VERSION_MAJOR:=1
VERSION_MINOR:=3
VERSION_MICRO:=0
PACKAGE_VERSION:=$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_MICRO)
VERSION:=$(PACKAGE_VERSION)
PREFIX=/usr/local

ENABLE_WSTRING_TESTS:=1
ENABLE_BOOST_THREAD_TESTS:=1
ENABLE_ZTHREAD_TESTS:=1
ENABLE_PTHREAD_TESTS:=1
